// <auto-generated />
using Garage_HomeWork_16.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Garage_HomeWork_16.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231226115441_RecentWorksAdded")]
    partial class RecentWorksAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Garage_HomeWork_16.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FilePath = "/services-01.jpg",
                            Text = "UI?UX Design text",
                            Title = "UI?UX Design"
                        },
                        new
                        {
                            Id = 2,
                            FilePath = "/services-02.jpg",
                            Text = "Social Media text",
                            Title = "Social Media"
                        },
                        new
                        {
                            Id = 3,
                            FilePath = "/services-03.jpg",
                            Text = "Marketing text",
                            Title = "Marketing"
                        },
                        new
                        {
                            Id = 4,
                            FilePath = "/services-04.jpg",
                            Text = "Graphic  text",
                            Title = "Graphic"
                        },
                        new
                        {
                            Id = 5,
                            FilePath = "/services-05.jpg",
                            Text = "Digital Marketing text",
                            Title = "Digital Marketing"
                        },
                        new
                        {
                            Id = 6,
                            FilePath = "/services-06.jpg",
                            Text = "Market Researchtext",
                            Title = "Market Research"
                        });
                });

            modelBuilder.Entity("Garage_HomeWork_16.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Business"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Marketing"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Social Media"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Graphic"
                        });
                });

            modelBuilder.Entity("Garage_HomeWork_16.Models.CategoryCategoryComponents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryComponentId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryComponentId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryCategoryComponents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryComponentId = 1,
                            CategoryId = 3
                        },
                        new
                        {
                            Id = 2,
                            CategoryComponentId = 1,
                            CategoryId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryComponentId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryComponentId = 2,
                            CategoryId = 4
                        },
                        new
                        {
                            Id = 5,
                            CategoryComponentId = 2,
                            CategoryId = 3
                        },
                        new
                        {
                            Id = 6,
                            CategoryComponentId = 3,
                            CategoryId = 2
                        },
                        new
                        {
                            Id = 7,
                            CategoryComponentId = 3,
                            CategoryId = 4
                        },
                        new
                        {
                            Id = 8,
                            CategoryComponentId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            Id = 9,
                            CategoryComponentId = 4,
                            CategoryId = 3
                        },
                        new
                        {
                            Id = 10,
                            CategoryComponentId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            Id = 11,
                            CategoryComponentId = 5,
                            CategoryId = 2
                        },
                        new
                        {
                            Id = 12,
                            CategoryComponentId = 6,
                            CategoryId = 2
                        },
                        new
                        {
                            Id = 13,
                            CategoryComponentId = 6,
                            CategoryId = 4
                        });
                });

            modelBuilder.Entity("Garage_HomeWork_16.Models.CategoryComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoryComponents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit,\r\nsed do eiusmod tempor incididunt ut labore et dolor.",
                            FilePath = "our-work-01.jpg",
                            Title = "Digital Marketing"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ut enim ad minim veniam, quis nostrud exercitation ullamco\r\nlaboris nisi ut aliquip ex ea commodo consequat.",
                            FilePath = "our-work-02.jpg",
                            Title = "Corporate Branding"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Duis aute irure dolor in reprehenderit in voluptate velit\r\nesse cillum dolore eu fugiatdolore eu fugiat nulla pariatur.",
                            FilePath = "our-work-03.jpg",
                            Title = "Leading Digital Solution"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in\r\nculpa qui officia deserunt mollit anim id est laborum.",
                            FilePath = "our-work-04.jpg",
                            Title = "Smart Applications"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Excepteur sint occaecat cupidatat non proident,\r\nsunt in culpa qui officia deserunt mollit anim id est laborum.",
                            FilePath = "our-work-05.jpg",
                            Title = "Corporate Stationary"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Ut enim ad minim veniam, quis nostrud exercitation ullamco\r\nlaboris nisi ut aliquip ex ea commodo consequat.",
                            FilePath = "our-work-06.jpg",
                            Title = "8 Financial Tips"
                        });
                });

            modelBuilder.Entity("Garage_HomeWork_16.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contact");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices\r\ngravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. Laboris\r\nnisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit\r\nin voluptate.",
                            Text = "Elit, sed do eiusmod tempor",
                            Title = "Create success campaign with us!"
                        });
                });

            modelBuilder.Entity("Garage_HomeWork_16.Models.ContactCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ContactId")
                        .HasColumnType("int");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconClassName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("ContactCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactId = 1,
                            Fullname = "Mr. John Doe",
                            IconClassName = "news",
                            PhoneNumber = "010-020-0340",
                            Title = "Media Contact"
                        },
                        new
                        {
                            Id = 2,
                            ContactId = 1,
                            Fullname = "Mr. John Stiles",
                            IconClassName = "laptop",
                            PhoneNumber = "010-020-0340",
                            Title = "Technical Contact"
                        },
                        new
                        {
                            Id = 3,
                            ContactId = 1,
                            Fullname = "Mr. Richard Miles",
                            IconClassName = "money",
                            PhoneNumber = "010-020-0340",
                            Title = "Billing Contact"
                        });
                });

            modelBuilder.Entity("Garage_HomeWork_16.Models.ContactIntro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactIntro");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "<h3 class=\"h4 regular-400\">Elit, sed do eiusmod tempor</h3><p class=\"light-300\">Vector illustration is from <a rel=\"nofollow\" href=\"https://storyset.com/\" target=\"_blank\">StorySet</a>.Incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida.</p>",
                            FilePath = "/banner-img-01.svg",
                            Title = "Contact"
                        });
                });

            modelBuilder.Entity("Garage_HomeWork_16.Models.RecentWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RecentWorks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagePath = "/assets/img/recent-work-01.jpg",
                            Text = "Ullamco laboris nisi ut aliquip ex",
                            Title = "Social Media"
                        },
                        new
                        {
                            Id = 2,
                            ImagePath = "/assets/img/recent-work-02.jpg",
                            Text = "Psum officia anim id est laborum.",
                            Title = "Web Marketing"
                        },
                        new
                        {
                            Id = 3,
                            ImagePath = "/assets/img/recent-work-03.jpg",
                            Text = "Sum dolor sit consencutur",
                            Title = "R & D"
                        },
                        new
                        {
                            Id = 4,
                            ImagePath = "/assets/img/recent-work-04.jpg",
                            Text = "Lorem ipsum dolor sit amet",
                            Title = "Public Relation"
                        },
                        new
                        {
                            Id = 5,
                            ImagePath = "/assets/img/recent-work-05.jpg",
                            Text = "Put enim ad minim veniam",
                            Title = "Branding"
                        },
                        new
                        {
                            Id = 6,
                            ImagePath = "/assets/img/recent-work-06.jpg",
                            Text = "Mollit anim id est laborum.",
                            Title = "Creative Design"
                        });
                });

            modelBuilder.Entity("Garage_HomeWork_16.Models.CategoryCategoryComponents", b =>
                {
                    b.HasOne("Garage_HomeWork_16.Models.CategoryComponent", null)
                        .WithMany()
                        .HasForeignKey("CategoryComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Garage_HomeWork_16.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Garage_HomeWork_16.Models.ContactCard", b =>
                {
                    b.HasOne("Garage_HomeWork_16.Models.Contact", "Contact")
                        .WithMany("ContactCards")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Garage_HomeWork_16.Models.Contact", b =>
                {
                    b.Navigation("ContactCards");
                });
#pragma warning restore 612, 618
        }
    }
}
